package com.hykj.liuzhi.androidcomponents.net.http;

public class ApiConstant {
    //正式
    public static final String ROOT_URL = "http://liuzhi.365hy.com";
    public static final String LOGIN = "/api/index/login";
    public static final String REGISTER = "/api/index/register";
    public static final String GETUSERSELF = "/api/index/getuserself";
    //用户关注的人
    public static final String GETUSERCOLLECTION = "/api/index/getusercollection";
    //用户的粉丝
    public static final String USER_FAN = "/api/index/getuserfanse";
    //用户点击按钮 关注/已关注
    public static final String USER_CLICK_ATTENTION = "/api/index/userfans";
    //用户上传图文信息
    public static final String USER_ADD_IMAGTEXT = "/api/index/addimagetext";
    //首页=推荐
    public static final String Home_Firstpagedata = "/api/index/firstpagedata";
    //首页=纹理
    public static final String Home_Firstpagedatatexture = "/api/index/firstpagedatatexture";
    //首页=潮流
    public static final String Home_Firstpagedatatrend = "/api/index/firstpagedatatrend";
    //首页=搜索历史
    public static final String Home_Userselecthistory = "/api/index/userselecthistory";
    //首页=搜索
    public static final String Home_Userselect = "/api/index/userselect";
    //首页=签到
    public static final String Home_SignIn = "/api/index/signin";
    //我的=签名
    public static final String Min_Changeautograph = "/api/index/changeautograph";
    //我的=昵称
    public static final String Min_Changenickname = "/api/index/changenickname";
    //我的=邮箱
    public static final String Min_ChangEmail = "/api/index/changemail";
    //我的=上传头像
    public static final String Min_ChangeUserPic = "/api/index/changeuserpic";
    //我的=收藏
    public static final String Min_UserCollection = "/api/index/usercollection";
    //我的=更改密码
    public static final String Min_ChangePassword = "/api/index/changepassword";
    //我的=实名认证
    public static final String Min_userfileuploads = "/api/index/userfileuploads";
    //我的=登录记录
    public static final String Min_logonrecord = "/api/index/logonrecord";
    //我的=用户所有的收货地址
    public static final String Min_getUserAddress = "/api/index/getuseraddress";
    //我的=添加收货地址
    public static final String Min_addshopaddress = "/api/index/addshopaddress";
    //我的=省
    public static final String Min_getprovinces = "/api/index/getprovinces";
    //我的=市
    public static final String Min_getcitys = "/api/index/getcitys";
    //我的=区
    public static final String Min_getareas = "/api/index/getareas";
    //我的=获取所有标签
    public static final String Min_getlabels = "/api/index/getlabels";
    //我的=修改标签
    public static final String Min_changelabel = "/api/index/changelabel";
    //图文(圈)=图文添加
    public static final String Circle_AddImageText = "/api/index/addimagetext";
    //商=获取轮播图片
    public static final String Shop_Getsowing = "/api/index/getsowing";
    //商=商品展示
    public static final String Shop_Goodsfirstpage = "/api/index/goodsfirstpage";
    //商=商品详情
    public static final String Shop_showgoods = "/api/index/showgoods";
    //商=商品收藏
    public static final String Shop_goodscollection = "/api/index/goodscollection";
    //商=商品取消收藏
    public static final String Shop_goodsnotcollection = "/api/index/goodsnotcollection";
    //商=添加购物车
    public static final String Shop_addshopcar = "/api/index/addshopcar";
    //商=查看购物车
    public static final String Shop_showshopcar = "/api/index/showshopcar";
    //商=添加订单
    public static final String Shop_addorders = "/api/index/addorders";
    //商=查看用户订单
    public static final String Shop_userorders = "/api/index/userorders";
    //商=用户商品搜索历史
    public static final String Shop_usergoodsselecthistory = "/api/index/usergoodsselecthistory";
    //商=商品搜素历史
    public static final String Shop_goodsselecthistory = "/api/index/goodsselecthistory";
    //商=商品查询
    public static final String Shop_selectgoods = "/api/index/selectgoods";
    //视频=查看视频
    public static final String Home_videoshow = "/api/index/videoshow";
    //视频=视频收藏
    public static final String Home_videocollection = "/api/index/videocollection";
    //视频=视频取消收藏
    public static final String Home_videonotcollection = "/api/index/videonotcollection";
    //视频=视频取消赞
    public static final String Home_videoisnotpoint = "/api/index/videoisnotpoint";
    //视频=视频点赞
    public static final String Home_videoispoint = "/api/index/videoispoint";
    //视频=视频列表
    public static final String Home_videolist = "/api/index/videolist";
    //视频=视频评论
    public static final String Home_videomessage = "/api/index/videomessage";
    //视频=获取所有的视频评论
    public static final String Home_videomessageall = "/api/index/videomessageall";
    //视频=视频打赏
    public static final String Home_videoreward = "/api/index/videoreward";
    //图文=图文展示
    public static final String Cirde_imagetextfirstpage = "/api/index/imagetextfirstpage";
}
